#cloud-config
package_update: true
packages:
  - git
  - curl
  - jq
  # eBPF Tools & Dependencies
  - linux-tools-generic
  - linux-tools-generic
  - linux-headers-generic
  - linux-cloud-tools-generic
  - bpfcc-tools
  - clang
  - llvm
  - libbpf-dev
  - bpftool
